name: 'Chromatic'

on:
  push:
    paths:
    - next/**

jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    env:
      workdir: 'next'
    # Job steps
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      working-directory: ${{ env.workdir }}
      run: npm i
      # 👇 Adds Chromatic as a step in the workflow
    - name: Publish to Chromatic
      uses: chromaui/action@v1
      # Chromatic GitHub Action options
      with:
        # 👇 Chromatic projectToken, refer to the manage page to obtain it.
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        workingDir: ${{ env.workdir }}
