name: MinIO Deploy to Fly
on:
  push:
    branches:
    - main
    paths:
    - minio/**
jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    # Deploy to production on main branch
    - run: cd minio && flyctl deploy --remote-only #-r mia
      if: github.ref == 'refs/heads/main'
      env:
        FLY_API_TOKEN: ${{ secrets.PROD_FLY_API_TOKEN }}
