name: Strapi Deploy to Fly
on:
  push:
    branches:
    - main
    - staging
    paths:
    - strapi/**
jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    # Deploy to staging on staging branch
    - run: cd strapi && flyctl -a REPLACE_ME-strapi-staging deploy --remote-only #-r cdg
      if: github.ref == 'refs/heads/staging'
      env:
        FLY_API_TOKEN: ${{ secrets.STG_FLY_API_TOKEN }}
    # Deploy to production on main branch
    - run: cd strapi && flyctl -a REPLACE_ME-strapi-prod deploy --remote-only #-r cdg
      if: github.ref == 'refs/heads/main'
      env:
        FLY_API_TOKEN: ${{ secrets.PROD_FLY_API_TOKEN }}
